Черняков Матвей Сергеевич
czertyaka/CppDevCourse-hw2 pull request #24
Opened 2024-11-27 13:46 UTC by mruax

2024-12-08 10:53 UTC, czertyaka requested changes

2024-12-08 10:53 UTC, czertyaka commented on main.cpp
> +    std::cout << "Hello World!" << std::endl;
Запятой не хватает, тесты не пройдут

2024-12-10 20:55 UTC, mruax commented on main.cpp
> +    std::cout << "Hello World!" << std::endl;
Исправил.

2024-12-15 18:39 UTC, czertyaka commented
Задание принято

2024-12-15 18:39 UTC, closed without merging