Артюшин Артём Александрович
czertyaka/CppDevCourse-hw2 pull request #41
Opened 2024-12-07 08:29 UTC by A1r3t0

2024-12-08 11:06 UTC, czertyaka requested changes
Директорию сборки и скомпилированную программу надо убрать из Git

2024-12-08 11:06 UTC, czertyaka commented on main.cpp
> +std::cout << "Hello, World!" << std::endl;
Обычно в тело функции выделяется отступом, например:
```c++
int main() {
    std::cout << "Hello, World!" << std::endl;
}
```

2024-12-14 13:03 UTC, A1r3t0 commented on main.cpp
> +std::cout << "Hello, World!" << std::endl;
Добавил tab в тело метода main(), директорию сборки и скомпилированную программу также убрал из репозитория

2024-12-15 18:40 UTC, czertyaka commented
Задание принято

2024-12-15 18:40 UTC, czertyaka commented
Задание принято

2024-12-15 18:40 UTC, closed without merging